<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Bhoomi Tulsiyani | 23010101275</b></center>    

<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 1</b></center>    
<pre>

# NumPy Exercises
## We'll start off with a few simple tasks

## import numpy as np

In [3]:
import numpy as np

In [48]:
arr = np.array(['1', '2', '3', '4'])

In [50]:
arr

array(['1', '2', '3', '4'], dtype='<U1')

In [16]:
type(arr)

numpy.ndarray

In [52]:
arr.dtype

dtype('<U1')

## Create an array of 10 zeros

In [42]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Create an array of 10 ones

In [54]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Create an array of 10 fives

In [62]:
np.linspace(5,5,10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [64]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## Create an array of the integers from 10 to 50

In [71]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

## Create a 3x3 matrix with values ranging from 0 to 8

In [75]:
arr = np.arange(0,9)

In [79]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Create a 3x3 identity matrix

In [83]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create following matrix  = <br/>
<pre>array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])</pre>

In [5]:
arr = np.arange(1,26).reshape(5,5)

In [7]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Output should be =
<pre>array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])</pre>

In [9]:
arr[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

## Output should be = <br/>
<pre>array([[ 2],
       [ 7],
       [12]])</pre>

In [110]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

## Find Odd Numbers
Extract all odd numbers from `arr`.

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])` <BR>
Use Condtional Selection

In [112]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

## Stacking
Stack array `a` and `b` vertically.

`a = np.arange(10).reshape(2,-1)`
`b = np.repeat(1, 10).reshape(2,-1)`

In [126]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)

In [128]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [130]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [156]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##  Range Filtering
Get all items between 5 and 10 from `a`.

`a = np.array([2, 6, 1, 9, 10, 3, 27])`

In [158]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [193]:
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

## Matrix Multiplication
Multiply a 5x3 matrix by a 3x2 matrix (dot product).

In [195]:
A = np.random.random((5,3))
B = np.random.random((3,2))

In [197]:
A

array([[0.84323596, 0.85775708, 0.5878795 ],
       [0.68472889, 0.8178762 , 0.35099494],
       [0.27928432, 0.79264958, 0.68178102],
       [0.05559577, 0.11798311, 0.09362291],
       [0.34640489, 0.46153493, 0.64652505]])

In [199]:
B

array([[0.11050015, 0.82018542],
       [0.15858034, 0.97748137],
       [0.93658238, 0.95117029]])

In [208]:
np.dot(A,B)

array([[0.7797987 , 2.08922492],
       [0.53409742, 1.69491936],
       [0.79510369, 1.65235497],
       [0.11253871, 0.24997646],
       [0.71699213, 1.35021345]])

In [212]:
A@B

array([[0.7797987 , 2.08922492],
       [0.53409742, 1.69491936],
       [0.79510369, 1.65235497],
       [0.11253871, 0.24997646],
       [0.71699213, 1.35021345]])

In [216]:
np.matmul(A,B)

array([[0.7797987 , 2.08922492],
       [0.53409742, 1.69491936],
       [0.79510369, 1.65235497],
       [0.11253871, 0.24997646],
       [0.71699213, 1.35021345]])

# Great Job! You’re Halfway Through 🚀  | PANDAS  Exercises

 **Context:** You are a Data Analyst at "TechCorp". 
HR has asked you to analyze employee data to understand attrition, salary trends, and job satisfaction.

**Instructions:**
1. Write your code in the empty cells.

### 1. Load & Inspect
Load `employee_data.csv` into a DataFrame named `df`. Display the first 5 rows and check column data types.

In [210]:
import pandas as pd

In [218]:
data = pd.read_csv('employee_data.csv')

In [220]:
data

,EmployeeID,Age,Department,JobRole,Attrition,MonthlyIncome,YearsAtCompany,JobSatisfaction,PerformanceRating,PercentSalaryHike,DistanceFromHome,MaritalStatus
0,1001,50,Research & Development,Data Scientist,No,8415,19,1,4,16,20,Married
1,1002,36,Research & Development,Data Scientist,No,6391,19,3,4,21,21,Married
2,1003,29,Sales,Data Scientist,No,14157,17,1,4,22,18,Married
3,1004,42,Sales,Sales Exec,No,14835,13,3,4,18,24,Married
4,1005,40,Sales,Software Engineer,No,8951,16,4,3,22,27,Single
...,...,...,...,...,...,...,...,...,...,...,...,...
195,1196,40,Research & Development,Sales Exec,Yes,9704,7,4,3,10,29,Married
196,1197,41,Sales,Lab Technician,No,7422,17,3,3,12,15,Divorced
197,1198,53,Research & Development,Data Scientist,No,12984,7,3,3,23,28,Divorced
198,1199,28,Sales,Software Engineer,No,4759,14,4,3,21,3,Married
199,1200,54,Research & Development,Sales Exec,Yes,14404,15,1,3,19,8,Single

In [222]:
data.head(5)

,EmployeeID,Age,Department,JobRole,Attrition,MonthlyIncome,YearsAtCompany,JobSatisfaction,PerformanceRating,PercentSalaryHike,DistanceFromHome,MaritalStatus
0,1001,50,Research & Development,Data Scientist,No,8415,19,1,4,16,20,Married
1,1002,36,Research & Development,Data Scientist,No,6391,19,3,4,21,21,Married
2,1003,29,Sales,Data Scientist,No,14157,17,1,4,22,18,Married
3,1004,42,Sales,Sales Exec,No,14835,13,3,4,18,24,Married
4,1005,40,Sales,Software Engineer,No,8951,16,4,3,22,27,Single

In [231]:
data.dtypes

EmployeeID            int64
Age                   int64
Department           object
JobRole              object
Attrition            object
MonthlyIncome         int64
YearsAtCompany        int64
JobSatisfaction       int64
PerformanceRating     int64
PercentSalaryHike     int64
DistanceFromHome      int64
MaritalStatus        object
dtype: object

### 2. Filter IT Department
Create a DataFrame `df_rd` containing only employees from the `'Research & Development'` department.

In [237]:
df_rd = data[data['Department'] == 'Research & Development']

In [243]:
df_rd.head()

,EmployeeID,Age,Department,JobRole,Attrition,MonthlyIncome,YearsAtCompany,JobSatisfaction,PerformanceRating,PercentSalaryHike,DistanceFromHome,MaritalStatus
0,1001,50,Research & Development,Data Scientist,No,8415,19,1,4,16,20,Married
1,1002,36,Research & Development,Data Scientist,No,6391,19,3,4,21,21,Married
5,1006,44,Research & Development,HR Manager,Yes,8468,8,4,3,12,11,Single
6,1007,32,Research & Development,Data Scientist,No,11007,19,2,3,19,2,Married
8,1009,45,Research & Development,Data Scientist,No,12444,1,3,3,16,18,Married

### 3. Salary Check
Find the employee with the highest `MonthlyIncome`. Display their `JobRole` and `MonthlyIncome`.

In [247]:
maxSalary = data['MonthlyIncome'].max()

In [249]:
print(maxSalary)

14954

In [275]:
data[['JobRole','MonthlyIncome']][data['MonthlyIncome']==maxSalary]

       JobRole  MonthlyIncome
28  HR Manager          14954

In [255]:
highest = data.sort_values('MonthlyIncome',ascending=False).iloc[0]

In [259]:
highest[['JobRole','MonthlyIncome']]

JobRole          HR Manager
MonthlyIncome         14954
Name: 28, dtype: object

### 4. Missing Values
Check if there are any missing values (`NaN`) in the dataset.

In [289]:
data.isnull().sum()

EmployeeID           0
Age                  0
Department           0
JobRole              0
Attrition            0
MonthlyIncome        0
YearsAtCompany       0
JobSatisfaction      0
PerformanceRating    0
PercentSalaryHike    0
DistanceFromHome     0
MaritalStatus        0
dtype: int64

### 5. Average Age by Role
Calculate the average `Age` for each `JobRole`.

In [291]:
data.groupby('JobRole')['Age'].mean()

JobRole
Data Scientist       38.771429
HR Manager           39.926829
Lab Technician       38.673469
Sales Exec           44.000000
Software Engineer    40.395349
Name: Age, dtype: float64

### 6. Attrition Count
How many employees have left the company? (Count values in the `Attrition` column).

In [312]:
data['Attrition'].value_counts()

Attrition
No     167
Yes     33
Name: count, dtype: int64

### 7. High Performers
Filter for employees with `PercentSalaryHike` > 15 **AND** `PerformanceRating` == 4.

In [322]:
data[(data['PercentSalaryHike'] > 15) & (data['PerformanceRating'] == 4)]

,EmployeeID,Age,Department,JobRole,Attrition,MonthlyIncome,YearsAtCompany,JobSatisfaction,PerformanceRating,PercentSalaryHike,DistanceFromHome,MaritalStatus
0,1001,50,Research & Development,Data Scientist,No,8415,19,1,4,16,20,Married
1,1002,36,Research & Development,Data Scientist,No,6391,19,3,4,21,21,Married
2,1003,29,Sales,Data Scientist,No,14157,17,1,4,22,18,Married
3,1004,42,Sales,Sales Exec,No,14835,13,3,4,18,24,Married
16,1017,59,Sales,Software Engineer,Yes,10577,6,2,4,16,23,Divorced
25,1026,37,Human Resources,Data Scientist,No,12510,19,4,4,17,10,Single
29,1030,28,Research & Development,Software Engineer,No,10804,18,3,4,21,18,Divorced
37,1038,47,Research & Development,Software Engineer,No,5192,3,3,4,24,15,Married
40,1041,49,Research & Development,Sales Exec,Yes,7033,15,1,4,21,2,Married
45,1046,38,Research & Development,Software Engineer,No,14302,14,1,4,19,11,Single
46,1047,57,Research & Development,Sales Exec,No,4970,11,2,4,22,10,Married
51,1052,50,Research & Development,Sales Exec,No,11135,16,4,4,21,8,Divorced
60,1061,29,Research & Development,Lab Technician,No,3922,4,3,4,18,4,Single
75,1076,45,Research & Development,HR Manager,No,14045,2,2,4,19,9,Married
77,1078,29,Research & Development,Data Scientist,No,10326,3,4,4,22,9,Married
103,1104,35,Research & Development,Lab Technician,No,13541,4,1,4,23,1,Single
108,1109,35,Sales,Sales Exec,No,10783,5,2,4,23,21,Single
110,1111,30,Research & Development,Lab Technician,No,14473,12,1,4,16,1,Divorced
118,1119,51,Research & Development,Software Engineer,No,7451,10,2,4,18,29,Divorced
120,1121,44,Research & Development,Sales Exec,No,6876,17,1,4,21,1,Married
128,1129,49,Research & Development,Lab Technician,No,8109,11,2,4,21,3,Married
151,1152,53,Sales,Sales Exec,No,14694,9,1,4,21,16,Divorced
157,1158,58,Research & Development,Data Scientist,No,7212,8,4,4,18,11,Divorced
174,1175,32,Research & Development,HR Manager,No,4205,17,2,4,20,28,Single
181,1182,43,Sales,Data Scientist,Yes,7757,8,3,4,24,4,Married
185,1186,30,Research & Development,Data Scientist,No,14312,6,1,4,22,19,Single
187,1188,37,Sales,Data Scientist,No,7944,18,1,4,16,14,Divorced

### 8. Satisfaction Analysis (Pivot Table)
Create a pivot table showing the **average** `MonthlyIncome` for each `Department` (rows) broken down by `JobSatisfaction` (columns).

In [335]:
pivot = data.pivot_table(index='Department',columns='JobSatisfaction',values='MonthlyIncome',aggfunc='mean')

In [337]:
pivot

JobSatisfaction                    1            2            3            4
Department
Human Resources          8494.666667  8822.200000  8196.333333  7744.833333
Research & Development  10810.718750  8581.125000  8648.090909  8930.304348
Sales                    9795.789474  9590.461538  8459.461538  9045.000000

### 9. Feature Engineering (Seniority)
Create a new column `Seniority`.
* If `YearsAtCompany` > 10, value is `'Senior'`
* Otherwise, value is `'Junior'`

Count how many Seniors vs Juniors there are.

In [339]:
data['Seniority'] = np.where(data['YearsAtCompany'] > 10, 'Senior', 'Junior')

In [344]:
data['Seniority'].value_counts()

Seniority
Junior    104
Senior     96
Name: count, dtype: int64

### 10. Retention Risk (Complex Filter)
Identify 'High Risk' employees who meet **ALL** these criteria:
1. `MaritalStatus` is 'Single'
2. `JobSatisfaction` is less than 3
3. `DistanceFromHome` > 10

Display their `EmployeeID` and `JobRole`.

In [351]:
data[['EmployeeID','JobRole']][(data['MaritalStatus'] == 'Single') & (data['JobSatisfaction'] < 3) & (data['DistanceFromHome'] > 10)]

     EmployeeID            JobRole
20         1021  Software Engineer
30         1031     Lab Technician
42         1043         HR Manager
43         1044         HR Manager
45         1046  Software Engineer
78         1079     Data Scientist
93         1094     Lab Technician
108        1109         Sales Exec
112        1113     Data Scientist
119        1120  Software Engineer
124        1125         HR Manager
159        1160         HR Manager
161        1162     Data Scientist
168        1169         HR Manager
169        1170         Sales Exec
172        1173  Software Engineer
174        1175         HR Manager
183        1184     Lab Technician
185        1186     Data Scientist